# To share info between Steps within a single job use Environment vars
name: env-vars
on: 
  push:
    branches: [env_vars]
jobs:
  set-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: set-env-vars
        run: echo 'MY_ENV_VAR=myValue' >> $GITHUB_ENV
      - name: use-env-vars
        run: | 
          echo "The value of MY_ENV_VAR is $MY_ENV_VAR"
      - name: store-build-time
        run: echo "BUILT_TIME=$(date + '%T')" >> $GITHUB_ENV
      - name: use-build-time
        run: printf '%s\n' "$BUILT_TIME"

    # multi-string
      - name: store-multiline
        id: step-two
        run: |
          {
            echo 'JSON_RESPONSE <<EOF'
            curl https://example.com
            echo EOF
          } >> "$GITHUB_ENV"
      - name: use-multiline
        run:   echo "$JSON_RESPONSE"