# To share info between separate jobs, use outputs
name: set-output
on:
  push: 
    branches: [set-output]
jobs:
  set-output:
    runs-on: ubuntu-latest
    steps:
      - name: set-color
        id: color-selector
        run: echo "SELECTED_COLOR=blue" >> "$GITHUB_OUTPUT"
    outputs:
      my_output: ${{ steps.color-selector.outputs.SELECTED_COLOR}}

  use-output:
    needs: set-output
    runs-on: ubuntu-latest
    steps:
      - name: get-color
        env:
          SELECTED_COLOR: ${{ needs.set-output.outputs.my_output }}
        run: echo "Color is $SELECTED_COLOR"