name: run-script
on: 
  push:
    branches: run-script
jobs:
  run-script:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: .github/scripts
    steps:
      - name: checkout-repo-to-runner
        uses: actions/checkout@v4
      - name: update-script-perm
        run: chmod +x test.sh
      - name: run-script
        run: ./test.sh
