name: store-output
on:
  push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4
      
      - name: npm-install-build-test
        run: |
          npm install
          npm run build --if-present
          npm test
      
      - name: archive-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          retention-days: 2
          path: |
            dist
            !dist/**/*.md

      - name: archive-results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: .github/output/test/code-coverage.html
