name: gh-cli-comment
on:
  issues:
    types:
      - opened
jobs:
  gh-cli-comment:
    runs-on: ubuntu-latest
    steps:
      - run: gh issue comment $ISSUE --body "my comment"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}